name: hw2_env2
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
#  - nb_conda
#  - notebook
#  - torchvision
  - opencv=4.5.2
  - pytorch=1.7.0
  - pytorch-lightning=1.3.6
  - cudatoolkit=11
  - pandas=1.2.4
  - matplotlib=3.4.2
  - pip
  - pip:
    - git+https://github.com/scaperex/vision.git #@v0.8.1