name: hw2_env
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3
  - nb_conda
  - notebook
  - pip
  - torchvision
  - opencv
  - pytorch
  - pytorch-lightning
  - cudatoolkit