name: hw2_env
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
#  - nb_conda
#  - notebook
#  - torchvision
  - opencv
  - pytorch
  - pytorch-lightning
  - cudatoolkit
  - pandas
  - matplotlib
  - pip
  - pip:
    - git+https://github.com/scaperex/vision.git #@v0.8.1