name: hw2_env2
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - opencv=4.5.2
  - pytorch=1.9.0
  - pytorch-lightning=1.3.6
#  - cudatoolkit=11.1.1
  - pandas=1.2.4
  - matplotlib=3.4.2
  - pip
  - pip:
    - googledrivedownloader==0.4
    - git+https://github.com/scaperex/vision.git